/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/adsdas': RouteRecordInfo<'/posts/adsdas', '/posts/adsdas', Record<never, never>, Record<never, never>>,
    '/posts/asda': RouteRecordInfo<'/posts/asda', '/posts/asda', Record<never, never>, Record<never, never>>,
    '/posts/asdasaf': RouteRecordInfo<'/posts/asdasaf', '/posts/asdasaf', Record<never, never>, Record<never, never>>,
    '/posts/asde': RouteRecordInfo<'/posts/asde', '/posts/asde', Record<never, never>, Record<never, never>>,
    '/posts/asdl': RouteRecordInfo<'/posts/asdl', '/posts/asdl', Record<never, never>, Record<never, never>>,
    '/posts/asdpwp': RouteRecordInfo<'/posts/asdpwp', '/posts/asdpwp', Record<never, never>, Record<never, never>>,
    '/posts/b': RouteRecordInfo<'/posts/b', '/posts/b', Record<never, never>, Record<never, never>>,
    '/posts/c': RouteRecordInfo<'/posts/c', '/posts/c', Record<never, never>, Record<never, never>>,
    '/posts/das': RouteRecordInfo<'/posts/das', '/posts/das', Record<never, never>, Record<never, never>>,
    '/posts/dasa': RouteRecordInfo<'/posts/dasa', '/posts/dasa', Record<never, never>, Record<never, never>>,
    '/posts/dasdd': RouteRecordInfo<'/posts/dasdd', '/posts/dasdd', Record<never, never>, Record<never, never>>,
    '/posts/ds': RouteRecordInfo<'/posts/ds', '/posts/ds', Record<never, never>, Record<never, never>>,
    '/posts/e': RouteRecordInfo<'/posts/e', '/posts/e', Record<never, never>, Record<never, never>>,
    '/posts/f': RouteRecordInfo<'/posts/f', '/posts/f', Record<never, never>, Record<never, never>>,
    '/posts/fasfth': RouteRecordInfo<'/posts/fasfth', '/posts/fasfth', Record<never, never>, Record<never, never>>,
    '/posts/g': RouteRecordInfo<'/posts/g', '/posts/g', Record<never, never>, Record<never, never>>,
    '/posts/h': RouteRecordInfo<'/posts/h', '/posts/h', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hon': RouteRecordInfo<'/posts/hon', '/posts/hon', Record<never, never>, Record<never, never>>,
    '/posts/kiw': RouteRecordInfo<'/posts/kiw', '/posts/kiw', Record<never, never>, Record<never, never>>,
    '/posts/lljsa': RouteRecordInfo<'/posts/lljsa', '/posts/lljsa', Record<never, never>, Record<never, never>>,
    '/posts/lll': RouteRecordInfo<'/posts/lll', '/posts/lll', Record<never, never>, Record<never, never>>,
    '/posts/oda': RouteRecordInfo<'/posts/oda', '/posts/oda', Record<never, never>, Record<never, never>>,
    '/posts/oo': RouteRecordInfo<'/posts/oo', '/posts/oo', Record<never, never>, Record<never, never>>,
    '/posts/ood': RouteRecordInfo<'/posts/ood', '/posts/ood', Record<never, never>, Record<never, never>>,
    '/posts/p': RouteRecordInfo<'/posts/p', '/posts/p', Record<never, never>, Record<never, never>>,
    '/posts/qw': RouteRecordInfo<'/posts/qw', '/posts/qw', Record<never, never>, Record<never, never>>,
    '/posts/sasdwe': RouteRecordInfo<'/posts/sasdwe', '/posts/sasdwe', Record<never, never>, Record<never, never>>,
    '/posts/zz': RouteRecordInfo<'/posts/zz', '/posts/zz', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
